version: 1.0.0.{build}
image: Visual Studio 2019

environment:
  matrix:
    - PlatformToolset: v142

platform:
  - x64
  - Win32

configuration:
  - Release
  - Debug

install:
  - if "%platform%"=="Win32" call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars32.bat"
  - if "%platform%"=="x64" call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"

build:
  parallel: true                  # enable MSBuild parallel builds
  verbosity: detailed

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - msbuild SelectQuotedText.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - ps: >-

      if ($env:PLATFORM -eq "x64") {
        Push-AppveyorArtifact "$env:PLATFORM\$env:CONFIGURATION\SelectQuotedText.dll" -FileName SelectQuotedText.dll
      }

      if ($env:PLATFORM -eq "Win32" ) {
        Push-AppveyorArtifact "$env:PLATFORM\$env:CONFIGURATION\SelectQuotedText.dll" -FileName SelectQuotedText.dll
      }

      if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v142") {
        if($env:PLATFORM -eq "x64") {
          $ZipFileName = "SelectQuotedText_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
          7z a $ZipFileName $env:PLATFORM\$env:CONFIGURATION\SelectQuotedText.dll
        }
        if($env:PLATFORM -eq "Win32") {
          $ZipFileName = "SelectQuotedText_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
          7z a $ZipFileName $env:PLATFORM\$env:CONFIGURATION\SelectQuotedText.dll
        }
      }

artifacts:
  - path: SelectQuotedText_*.zip
    name: releases

deploy:
  provider: GitHub
  auth_token:
    secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
  artifact: releases
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
    PlatformToolset: v142
    configuration: Release
